### ISSUE TITLE
400 Bad Request when sending data to submission service

### ISSUE THREAD

**Issue by timberhill** [flam-flam/dispatcher-service#8]
### Reproduce

In flam-flam/helm-charts repo:

```bash
cd compose && docker-compose up
```

### Logs:
```
dispatcher_1  | Failed to dispatch to http://submission:80/api/submissions, 400 Client Error: Bad Request for url: http://submission:80/api/submissions
```

### Expected behaviour

The request comes through and the payload is logged out in the submissions service container

**Comment by fratcliffe** [comment]
So the fix in #9 seems to work but I'm going to check that it works when running `docker compose up` from scratch with the PR branch in the [dispatcher build url](https://github.com/flam-flam/helm-charts/blob/main/compose/docker-compose.yaml#L6)

**Comment by fratcliffe** [comment]
✅

**Comment by timberhill** [comment]
LGTM :duck:
